Repository langfuse/langfuse-k8s, pull requests merged in 2024-10, with the labels that each got.

#31 fix: Have readinessProbe call /api/public/ready
  charts/langfuse/templates/deployment.yaml
Labels: size:XS, lgtm

#32 docs: Add Ingress and postgres storageClass to the README
  README.md
Labels: size:S, lgtm

#35 Resolves https://github.com/langfuse/langfuse-k8s/issues/34: Custom s…
  README.md
  charts/langfuse/Chart.yaml
  charts/langfuse/templates/deployment.yaml
  charts/langfuse/templates/nextauth-secret.yaml
  charts/langfuse/templates/postgresql-secret.yaml
Labels: size:M, lgtm
