Repository langfuse/langfuse-k8s, pull requests merged in 2025-01, with the labels that each got.

#52 Skip NEXTAUTH_SECRET and SALT in worker when source values are null
  charts/langfuse/templates/deployment-worker.yaml
Labels: size:XS, lgtm

#57 Fix: specify resources for web and worker individually
  README.md
  charts/langfuse/Chart.yaml
  charts/langfuse/templates/deployment-web.yaml
  charts/langfuse/templates/deployment-worker.yaml
  charts/langfuse/templates/hpa-web.yaml
  charts/langfuse/templates/hpa-worker.yaml
  charts/langfuse/values.yaml
Labels: size:S, lgtm

#61 chore: add cluster mode note for replicaCount 1in clickhouse
  README.md
Labels: size:XS

#62 feat: upgrade dependency versions + clickhouse sizing guide
  README.md
  charts/langfuse/Chart.yaml
  charts/langfuse/values.yaml
Labels: size:S

#64 chore: bump clickhouse default resources
  README.md
  charts/langfuse/Chart.yaml
  charts/langfuse/values.yaml
Labels: size:XS
