Repository langfuse/langfuse-k8s, pull requests merged in 2025-03, with the labels that each got.

#87 chore: update docs around auto migration
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
Labels: size:XS

#88 enable TLS for Redis
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
  charts/langfuse/values.yaml
Labels: size:M

#89 feat: add annotation support
  UPGRADE.md
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/templates/web/deployment.yaml
  charts/langfuse/templates/worker/deployment.yaml
  charts/langfuse/values.yaml
Labels: size:M

#92 feat: add s3 concurrency options
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
  charts/langfuse/values.yaml
Labels: size:S

#95 fix: overwrite region default for eventUpload
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/values.yaml
Labels: size:XS

#99 chore: document use of custom storage classes
  README.md
  charts/langfuse/README.md
  charts/langfuse/values.yaml
Labels: size:M

#100 updated clickhouse helm chart version
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
Labels: size:XS

#104 chore: create 1.0.0 release
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
Labels: size:XS

#106 fix: update yaml indentation in readme
  README.md
Labels: size:M, lgtm
