Repository langfuse/langfuse-k8s, pull requests merged in 2025-05, with the labels that each got.

#151 build: publish chart to github container registry
  .github/workflows/release.yaml
Labels: size:M

#152 Fix S3 Upload Type Specific Endpoint Configuration
  charts/langfuse/templates/_helpers.tpl
Labels: size:S, lgtm

#154 docs: add sizing guide to helm readme
  README.md
Labels: size:M

#159 chore: bump langfuse version
  UPGRADE.md
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
Labels: size:S

#160 fix: fallback to minio if its deployed
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
Labels: size:S

#156 feat: add more configs to values
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
  charts/langfuse/templates/validations.yaml
  charts/langfuse/values.yaml
Labels: size:M, lgtm

#158 Add langfuse.web.service.externalPort variable
  charts/langfuse/README.md
  charts/langfuse/templates/web/service.yaml
  charts/langfuse/values.yaml
Labels: size:XS, lgtm
