Repository langfuse/langfuse-k8s, pull requests merged in 2025-02, with the labels that each got.

#75 fix: parse service annotations to valid yaml
  charts/langfuse/Chart.yaml
  charts/langfuse/templates/service.yaml
Labels: size:S

#79 feat: prepare chart for 1.0.0 release
  .github/workflows/release.yaml
  .github/workflows/validate.yaml
  README.md
  UPGRADE.md
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
  charts/langfuse/templates/deployment-web.yaml
  charts/langfuse/templates/deployment-worker.yaml
  charts/langfuse/templates/ingress.yaml
  charts/langfuse/templates/nextauth-secret.yaml
  charts/langfuse/templates/postgresql-secret.yaml
  charts/langfuse/templates/serviceaccount.yaml
  charts/langfuse/templates/validations.yaml
  charts/langfuse/templates/web/deployment.yaml
  charts/langfuse/templates/web/hpa.yaml
  charts/langfuse/templates/web/service.yaml
  charts/langfuse/templates/web/vpa.yaml
  charts/langfuse/templates/worker/deployment.yaml
  charts/langfuse/templates/worker/hpa.yaml
  charts/langfuse/templates/worker/vpa.yaml
  charts/langfuse/values.lint.yaml
  charts/langfuse/values.yaml
  examples/langfuse-configmap.yaml
  examples/langfuse-deployment.yaml
  examples/langfuse-service.yaml
  examples/minimal-installation/README.md
  examples/minimal-installation/secret.yaml
  examples/minimal-installation/values.yaml
  examples/minimal-installation/with-ingress.yaml
  examples/upgrade-v0.13-to-v1.0/v0.13-values.yaml
  examples/upgrade-v0.13-to-v1.0/v1.0-values.yaml
  examples/values-example.yaml
Labels: size:XXL

#84 fix: Revert change in clickhouse resourcesPreset default
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/values.yaml
Labels: size:XS, lgtm
