Repository langfuse/langfuse-k8s, pull requests merged in 2025-04, with the labels that each got.

#119 feat: allow empty redis username
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
  charts/langfuse/values.yaml
Labels: size:M

#120 fix: propagate s3.auth.rootUserSecretKey to langfuse containers
  README.md
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
  charts/langfuse/values.yaml
Labels: size:M

#121 chore: add note on URL encoding for redis passwords
  charts/langfuse/README.md
  charts/langfuse/values.yaml
Labels: size:XS

#122 update: Update the example - s3 password is missing
  examples/minimal-installation/README.md
  examples/minimal-installation/secret.yaml
  examples/minimal-installation/values.yaml
Labels: size:S, lgtm

#127 fix: add ssl config for self-hosted clickhouse
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
Labels: size:XS

#128 chore: handle clickhouse protocol
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
Labels: size:M

#134 fix: do not set DATABASE_URL twice if configured via additionalEnv
  charts/langfuse/Chart.yaml
  charts/langfuse/README.md
  charts/langfuse/templates/_helpers.tpl
Labels: size:S

#124 feat: Adding langfuse to artifact hub
  LICENSE
  artifacthub-repo.yaml
Labels: size:XS

#123 docs: added langfuse artifact hub badge to docs
  README.md
Labels: size:XS, lgtm
